export enum PoliceRank {
  PGEN = 'PGEN',
  PLTGEN = 'PLTGEN',
  PMGEN = 'PMGEN',
  PBGEN = 'PBGEN',
  PCOL = 'PCOL',
  PLTCOL = 'PLTCOL',
  PMAJ = 'PMAJ',
  PCPT = 'PCPT',
  PLT = 'PLT',
  PEMS = 'PEMS',
  PCMS = 'PCMS',
  PSMS = 'PSMS',
  PMSg = 'PMSg',
  PSSg = 'PSSg',
  PCpl = 'PCpl',
  Pat = 'Pat',
  NONE = 'none',
}
